Milestone 2: Works section
theodoku/My-portfolio-project pull request #2
Opened 2023-01-12 22:22 UTC by theodoku

1. Create a new branch
2. Build the works section for portfolio
3. Create the about section
4. Style sections using the Figma template 1

2023-01-12 23:02 UTC, bienvenuushindi requested changes
Hi @theodoku  , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media0.giphy.com/media/cYaB1VycDbOyOiXcCx/giphy.gif"/>

## Highlights
May I highlight the following:

- The repo looks professional.:heavy_check_mark:
- There are no linter errors:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:
- Your project looks good:heavy_check_mark:

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-12 23:02 UTC, bienvenuushindi commented on style.css
> +.project-name {
:red_circle: Kindly make sure this CSS selector is applied on the right element(p-title) to match the Figma Design
It seems your p-title elements inherit the default font-size assigned by the browser.

Your Design (1.5rem or 48px is the current font-size applied to this element )
![your title](https://user-images.githubusercontent.com/26736582/212198279-460b66d7-4683-4a63-994d-ef3a7fd7a9c2.png)

Figma Design (32px)
![figma](https://user-images.githubusercontent.com/26736582/212198307-74f4dabd-78fb-431a-9c72-b878a2018c50.png)

An alternative solution would be to apply this font-size directly to p-title selector as follow :arrow_down: 

```
.p-title {
    font-size: 32px;
}
```

2023-01-12 23:02 UTC, bienvenuushindi commented on index.html
> +            </ul>
:red_circle: For semantics reason, Kindly make sure you wrap this block in a li tag as only li tag should be direct child of ul tag.

2023-01-13 09:17 UTC, brainconnect93 approved these changes
## Status: Approved :heavy_check_mark:

Hi @theodoku, 👋  

Your project is complete! Great job for following the project requirement🥇and implementing the changes requested by the previous reviewer. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 


<img src="https://i.pinimg.com/originals/f8/3d/cf/f83dcf0c379de146ef962251952577ab.gif">

## Good Points 👍

- Has a proper Pull Request. ✔️
- No Linter errors ✔️
- Good use of Github flow ✔️

## Optional changes

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brainconnect93 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-13 10:02 UTC, merged